Repository Team-Going/Going-iOS, pull requests merged in 2024-03, with the labels that each got.

#207 [FEAT] 성향테스트스플래쉬뷰 스킵 버튼 추가 (#206)
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
Labels: 🦦 성준, ✨ Feat

#208 [FEAT] 여행 수정뷰 구현 (#201)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UIColor+.swift
  Going-iOS/Global/Extensions/UILabel+.swift
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_tripinfo.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_tripinfo.imageset/btn_tripinfo.svg
  Going-iOS/Global/Resources/Assets.xcassets/btn_delete.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/btn_delete.imageset/btn_delete.svg
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Global/Utils/HapticService.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/Views/DatePickerView.swift
  Going-iOS/Scene/CreateTravel/Views/TravelDateView.swift
  Going-iOS/Scene/CreateTravel/Views/TravelNameView.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/Member/Views/MemberProgressView.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/EditTravelViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/QuitTravelPopUpViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/TravelInfoViewController.swift
Labels: 🐢 영서, ✨ Feat

#213 [FEAT] 여행 TODO 수정뷰 UI (#200)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Network/DTO/ToDo/Response/GetDetailToDoStruct.swift
  Going-iOS/Network/Services/ToDoService.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ActivateToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/ToDoManagerView.swift
  Going-iOS/Scene/ToDo/Views/ToDoTextFieldView.swift
Labels: 👩 희슬, ✨ Feat

#219 [FEAT] 여행 수정 및 여행친구취향뷰 UI / 서버통신 (#212)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Global/Extensions/UIView+.swift
  Going-iOS/Global/Resources/Assets.xcassets/Profile/img_profile_guest.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Profile/img_profile_guest.imageset/img_profile_guest.svg
  Going-iOS/Global/UserDefault/UserDefaultToken.swift
  Going-iOS/Network/DTO/Auth/Response/BasicResponseDTO.swift
  Going-iOS/Network/DTO/TravelDetail/Request/EditTravelRequestStruct.swift
  Going-iOS/Network/DTO/TravelDetail/Response/TravelDetailResponseStruct.swift
  Going-iOS/Network/DTO/Trip/Response/MemberResponseStruct.swift
  Going-iOS/Network/Services/MemberService.swift
  Going-iOS/Network/Services/TravelDetailService.swift
  Going-iOS/Scene/CreateTravel/Models/CreateTravelRequestAppData.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/Member/Models/MemberTestStruct.swift
  Going-iOS/Scene/Member/Models/MemberTravelTestStruct.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/Member/Views/AnswerProgressSection.swift
  Going-iOS/Scene/Member/Views/AnswerStackView.swift
  Going-iOS/Scene/Member/Views/AnswerType.swift
  Going-iOS/Scene/Member/Views/MemberMultiProgressView.swift
  Going-iOS/Scene/Member/Views/MemberProgressView.swift
  Going-iOS/Scene/Member/Views/MemberTestResultView.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/TravelTestResultView.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/EditTravelViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/TravelInfoViewController.swift
Labels: 🐢 영서, 🌐 Network, ✨ Feat

#222 [FEAT] 여행성향테스트분기처리 및 온보딩 플로우 변경(#218)
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Global/Settings/Configurations/Development.xcconfig
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, ✨ Feat

#226 [Feat] 여행나가기 서버통신 구현(#225)
  Going-iOS/Network/Services/TravelService.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/QuitTravelPopUpViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/TravelInfoViewController.swift
Labels: 🦦 성준, 🌐 Network

#227 [FEAT] 여행성향테스트 조회 및 수정 UI/서버통신 구현 (#221)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Network/DTO/Profile/Response/MemberProfileResponseStruct.swift
  Going-iOS/Network/DTO/TravelDetail/Request/EditTravelTestRequestStruct.swift
  Going-iOS/Network/Services/TravelDetailService.swift
  Going-iOS/Network/Services/TravelProfileService.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/TravelTestResultView.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/ViewControllers/EditTravelTestViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
Labels: 🐢 영서, 🌐 Network, ✨ Feat

#229 [FEAT] 내 프로필 & 친구 프로필 조회 서버 통신 (#220)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_tasteview.imageset/btn_tasteview.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_tasteview.imageset/btn_tasteview@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_tasteview.imageset/btn_tasteview@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/btn_enter.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/btn_enter.imageset/btn_enter 1.svg
  Going-iOS/Global/Resources/Assets.xcassets/btn_enter.imageset/btn_enter 2.svg
  Going-iOS/Global/Resources/Assets.xcassets/btn_enter.imageset/btn_enter.svg
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Network/DTO/Profile/Response/GetPersonalProfileDTO.swift
  Going-iOS/Network/Services/MemberService.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/MyProfileTopView.swift
  Going-iOS/Scene/MyProfile/Views/TravelTestResultView.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestCollectionViewCell.swift
  Going-iOS/Scene/ToDo/ViewControllers/ActivateToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 👩 희슬, 🌐 Network, ✨ Feat

#234 [FEAT] 기타 수정사항 반영 (#232)
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
Labels: 👩 희슬, Chore

#233 [FEAT] 여행성향테스트수정뷰 연결 구현 (#228)
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/EditTravelTestViewController.swift
Labels: 🐢 영서, ✨ Feat

#236 [FEAT] 우리의 여행취향뷰와 여행프로필뷰 연결 및 내 여행프로필 취향태그뷰 수정 (#235)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Resources/Assets.xcassets/no_friends_emptyImage.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/no_friends_emptyImage.imageset/no_friends_emptyImage.png
  Going-iOS/Global/Resources/Assets.xcassets/no_friends_emptyImage.imageset/no_friends_emptyImage@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/no_friends_emptyImage.imageset/no_friends_emptyImage@3x.png
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/Member/Views/NoFriendsEmptyView.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/EmptyUserTestView.swift
  Going-iOS/Scene/MyProfile/Views/TravelTestResultView.swift
  Going-iOS/Scene/MyProfile/Views/UserTestResultScrollView.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/Settings/Cells/SettingsCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestResultCollectionViewFooter.swift
  Going-iOS/Scene/StartTravel/ViewControllers/EditTravelTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🌐 Network, ✨ Feat

#238 [FEAT] 취향태그뷰 라이팅 수정 및 기타 수정 사항 (#237)
  Going-iOS/Scene/Member/Models/MemberTravelTestStruct.swift
  Going-iOS/Scene/Member/Views/NoFriendsEmptyView.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestResultCollectionViewFooter.swift
  Going-iOS/Scene/StartTravel/Models/TravelTestQuestionStruct.swift
Labels: 🐢 영서, ✨ Feat

#240 [Feat] 티켓뷰 내 titleLabel 생략되는 오류 수정 (#239)
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
Labels: 🐢 영서, ✨ Feat

#242 [FEAT] '혼자 할 일' 생성 오류 수정 (#241)
  Going-iOS/Scene/ToDo/ViewControllers/ActivateToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/ToDoManagerView.swift
Labels: 👩 희슬, ✨ Feat

#246 [FEAT] 사용성 관련 작업 구현 (#245)
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/MyProfileTopView.swift
  Going-iOS/Scene/PopUp/DeleteUserPopUp/DeleteUserPopUpViewController.swift
  Going-iOS/Scene/PopUp/InviteFriendPopUp/InviteFriendPopUpViewController.swift
  Going-iOS/Scene/PopUp/LogOutPopUp/LogOutPopUpViewController.swift
  Going-iOS/Scene/PopUp/PopUpDimmedViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ActivateToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/QuitTravelPopUpViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/TravelInfoViewController.swift
Labels: 🐢 영서, ✨ Feat

#249 [FEAT] 1차 QA 반영 (#247)
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock.svg
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock@3x.png
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/ChangeMyProfileViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/ToDo/Cells/ToDoManagerCollectionViewCell.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/MemoTextView.swift
  Going-iOS/Scene/ToDo/Views/ToDoTextFieldView.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/EditTravelViewController.swift
Labels: 👩 희슬, ✨ Feat

#252 [FEAT] 1차 QA 이슈 대응 (#248)
  Going-iOS/Global/Resources/Assets.xcassets/img_test_empty.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/img_test_empty.imageset/img_test_empty.png
  Going-iOS/Global/Resources/Assets.xcassets/img_test_empty.imageset/img_test_empty.svg
  Going-iOS/Global/Resources/Assets.xcassets/img_test_empty.imageset/img_test_empty@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/img_test_empty.imageset/img_test_empty@3x.png
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/EmptyUserTestView.swift
  Going-iOS/Scene/MyProfile/Views/MyProfileTopView.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/EditTravelViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/TravelInfoViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🐢 영서, ✨ Feat

#254 Feature/#251
  Going-iOS/Global/Extensions/String+.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyTravelProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/EmptyUserTestView.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/ToDo/ViewControllers/ActivateToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/MemoTextView.swift
  Going-iOS/Scene/ToDo/Views/ToDoManagerView.swift
  Going-iOS/Scene/ToDo/Views/ToDoTextFieldView.swift
Labels: 👩 희슬, ✨ Feat

#255 [FEAT] 1차 QA 대응(#250)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/ChangeMyProfileViewController.swift
  Going-iOS/Scene/PopUp/LogOutPopUp/LogOutPopUpViewController.swift
  Going-iOS/Scene/ToDo/Cells/ToDoManagerCollectionViewCell.swift
  Going-iOS/Scene/ToDo/Views/ToDoManagerView.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🦦 성준, ✨ Feat, Chore

#256 [FEAT] 1차 추가 QA 대응 (#253)
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/EditTravelViewController.swift
Labels: 🐢 영서, ✨ Feat
