Repository Team-Going/Going-iOS, pull requests merged in 2024-04, with the labels that each got.

#260 [Fix] 성향테스트뷰 볼드체 에러 해결(#258)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🦦 성준, ⚒️ Fix

#262 [FEAT] 2차 QA 이슈 대응 (#257)
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/ChangeMyProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/MyProfileTopView.swift
  Going-iOS/Scene/TravelDetail/ViewControllers/EditTravelViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🐢 영서, ✨ Feat

#261 [FEAT] 2차 QA 반영 (#259)
  Going-iOS/Global/Extensions/String+.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/ToDo/ViewControllers/ActivateToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/MemoTextView.swift
  Going-iOS/Scene/ToDo/Views/ToDoManagerView.swift
  Going-iOS/Scene/ToDo/Views/ToDoTextFieldView.swift
Labels: 👩 희슬, ✨ Feat

#266 [FEAT] 2차 추가 QA 대응 (#265)
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
Labels: 👩 희슬, ✨ Feat

#264 [FEAT] 2차 QA 추가 이슈 대응 (#263)
  Going-iOS/Network/DTO/Trip/Response/DashBoardResponseSturct.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/DashBoard/Views/DashBoardHeaderView.swift
  Going-iOS/Scene/MyProfile/ViewControllers/ChangeMyProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/EmptyUserTestView.swift
  Going-iOS/Scene/MyProfile/Views/MyProfileTopView.swift
  Going-iOS/Scene/MyProfile/Views/TravelProfileHeaderView.swift
  Going-iOS/Scene/MyProfile/Views/TravelTestResultView.swift
  Going-iOS/Scene/MyProfile/Views/UserTestResultScrollView.swift
Labels: 🐢 영서, ✨ Feat, ⚒️ Fix

#268 [FIX] 3차 QA
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
Labels: 🦦 성준, ⚒️ Fix

#270 [UPDATE] 1.2.0 업데이트 (#269)
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Global/Settings/Configurations/Development.xcconfig
Labels: 🦦 성준, 🚀 Update

#272 [HOTFIX] 여행생성/초대 완료뷰 라벨 정렬 수정 (#271)
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
Labels: 🐢 영서, 🛠️ Hotfix
