Repository Team-Going/Going-iOS, pull requests merged in 2024-01, with the labels that each got.

#18 [FEAT] 아워투두 UI 및 기능 구현 (#17)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UIColor+.swift
  Going-iOS/Global/Extensions/UIView+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_ourtodo_edit.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_ourtodo_edit.imageset/btn_ourtodo_edit1.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_ourtodo_edit.imageset/btn_ourtodo_edit@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_ourtodo_edit.imageset/btn_ourtodo_edit@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus.imageset/btn_plus.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus.imageset/btn_plus@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus.imageset/btn_plus@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus_ourtodo.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus_ourtodo.imageset/btn_plus_ourtodo.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus_ourtodo.imageset/btn_plus_ourtodo@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/btn_plus_ourtodo.imageset/btn_plus_ourtodo@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/ticket_box.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/ticket_box.imageset/ticket_box.svg
  Going-iOS/Global/Resources/Assets.xcassets/btn_back.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/btn_back.imageset/btn_back.svg
  Going-iOS/Global/Resources/Font/Pretendard-Black.otf
  Going-iOS/Global/Resources/Font/Pretendard-Bold.otf
  Going-iOS/Global/Resources/Font/Pretendard-ExtraBold.otf
  Going-iOS/Global/Resources/Font/Pretendard-ExtraLight.otf
  Going-iOS/Global/Resources/Font/Pretendard-Light.otf
  Going-iOS/Global/Resources/Font/Pretendard-Medium.otf
  Going-iOS/Global/Resources/Font/Pretendard-Regular.otf
  Going-iOS/Global/Resources/Font/Pretendard-SemiBold.otf
  Going-iOS/Scene/OurToDo/Cells/ManagerCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Models/FriendProfileData.swift
  Going-iOS/Scene/OurToDo/Models/OurToDoData.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/NavigationBarView.swift
  Going-iOS/Scene/OurToDo/Views/OurToDoHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/OurToDo/Views/UnderlineSegmentedControlView.swift
Labels: 👩 희슬, ✨ Feat

#19 [FEAT] 프로필생성뷰 UI 및 기능 구현 (#16)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/Constant.swift
  Going-iOS/Global/Utils/ScreenUtils.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/MakeProfile/MakeProfileViewController.swift
Labels: 🦦 성준, ✨ Feat

#21 [FEAT] 여행생성뷰 / 여행생성완료뷰 UI 및 기능 구현 (#14)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UITextField+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ic_copy.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ic_copy.imageset/ic_copy.png
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ic_copy.imageset/ic_copy@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ic_copy.imageset/ic_copy@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ticket_img_small.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ticket_img_small.imageset/ticket_img_small.png
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ticket_img_small.imageset/ticket_img_small@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/CreateTravel/ticket_img_small.imageset/ticket_img_small@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_back.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_back.imageset/btn_back.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_back.imageset/btn_back@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_back.imageset/btn_back@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_close.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_close.imageset/btn_close1.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_close.imageset/btn_close@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_close.imageset/btn_close@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_save.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_save.imageset/btn_save.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_save.imageset/btn_save@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/NavigationBar/btn_save.imageset/btn_save@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/Contents.json
  Going-iOS/Global/UIComponents/.gitkeep
  Going-iOS/Global/UIComponents/DOOButton.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/CreateTravel/Views/DatePickerView.swift
  Going-iOS/Scene/CreateTravel/Views/NavigationBarView.swift
  Going-iOS/Scene/CreateTravel/Views/NavigationView.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/CreateNavigationBar.swift
Labels: 🐢 영서, ✨ Feat

#24 [FEAT] 성향테스트뷰 UI 및 기능 구현, DOOLabel 생성 (#20)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/btn_ourtodo_edit.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/btn_ourtodo_edit.imageset/btn_ourtodo_edit.png
  Going-iOS/Global/Resources/Assets.xcassets/btn_ourtodo_edit.imageset/btn_ourtodo_edit@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/btn_ourtodo_edit.imageset/btn_ourtodo_edit@3x.png
  Going-iOS/Global/UIComponents/DOOLabel.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/Models/UserTestQuestionStruct.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🦦 성준, ✨ Feat

#28 [FEAT] 아워투두 할일 추가 UI 및 기능 구현 (#23)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Extensions/UILabel+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/disabled_ic_dropdown.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/disabled_ic_dropdown.imageset/disabled_ic_dropdown.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/disabled_ic_dropdown.imageset/disabled_ic_dropdown@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/disabled_ic_dropdown.imageset/disabled_ic_dropdown@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/enabled_ic_dropdown.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/enabled_ic_dropdown.imageset/enabled_ic_dropdown.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/enabled_ic_dropdown.imageset/enabled_ic_dropdown@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/enabled_ic_dropdown.imageset/enabled_ic_dropdown@3x.png
  Going-iOS/Global/UIComponents/PaddingLabel.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/ToDo/Cells/ToDoManagerCollectionViewCell.swift
  Going-iOS/Scene/ToDo/Models/ToDoData.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/DoubleButtonView.swift
Labels: 👩 희슬, ✨ Feat

#29 [FEAT] 여행취향테스트뷰 UI 및 기능 구현 (#26)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UICollectionViewCell+.swift
  Going-iOS/Global/Extensions/UITableViewCell+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/TravelTest/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/TravelTest/round_background_image.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/TravelTest/round_background_image.imageset/round_background_image.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelTest/round_background_image.imageset/round_background_image@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelTest/round_background_image.imageset/round_background_image@3x.png
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/CreateTravel/Views/DatePickerView.swift
  Going-iOS/Scene/CreateTravel/Views/NavigationView.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/OurToDo/Cells/ManagerCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/CreateNavigationBar.swift
  Going-iOS/Scene/OurToDo/Views/OurToDoHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/Models/TravelTestQuestionStruct.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
Labels: 🐢 영서, ✨ Feat

#31 [FEAT]UsetTestResultView UI 구현 (#27)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UIButton+.swift
  Going-iOS/Global/Extensions/UIView+.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, ✨ Feat

#34 [FEAT] 프로필완성뷰 UI 구현 및 성향테스트 결과 데이터더미 생성 (#32)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Scene/CompleteProfile/ViewControllers/CompleteProfileViewController.swift
  Going-iOS/Scene/UserTestResult/Models/UserTypeTestResultAppData.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, ✨ Feat

#38 [FEAT] 마이투두 UI 및 기능 구현 (#33)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_complete.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_complete.imageset/btn_checkbox_complete.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_complete.imageset/btn_checkbox_complete@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_complete.imageset/btn_checkbox_complete@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_incomplete.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_incomplete.imageset/btn_checkbox_incomplete.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_incomplete.imageset/btn_checkbox_incomplete@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/btn_checkbox_incomplete.imageset/btn_checkbox_incomplete@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_dark.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_dark.imageset/ic_lock_dark.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_dark.imageset/ic_lock_dark@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_dark.imageset/ic_lock_dark@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_light.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_light.imageset/ic_lock_light.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_light.imageset/ic_lock_light@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/ic_lock_light.imageset/ic_lock_light@3x.png
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/Models/MyToDoData.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/OurToDoHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
Labels: 👩 희슬, ✨ Feat

#40 [FEAT] 설정뷰 UI 구현
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/Settings/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Settings/btn_enter_large.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Settings/btn_enter_large.imageset/btn_enter_large.png
  Going-iOS/Global/Resources/Assets.xcassets/Settings/btn_enter_large.imageset/btn_enter_large@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Settings/btn_enter_large.imageset/btn_enter_large@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/Settings/ic_unsubscribe.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Settings/ic_unsubscribe.imageset/ic_unsubscribe.png
  Going-iOS/Global/Resources/Assets.xcassets/Settings/ic_unsubscribe.imageset/ic_unsubscribe@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Settings/ic_unsubscribe.imageset/ic_unsubscribe@3x.png
  Going-iOS/Scene/Settings/Cells/SettingsCollectionViewCell.swift
  Going-iOS/Scene/Settings/Models/SettingsItem.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
Labels: 🐢 영서, ✨ Feat

#42 [FEAT] 성향테스트결과뷰 수정, 프로필 생성뷰 수정 (#35)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/AppDelegate.swift
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Extensions/UIView+.swift
  Going-iOS/Global/Settings/Info.plist
  Going-iOS/Global/UIComponents/DOOLabel.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, ✨ Feat

#44 [FEAT] 이미지 저장 로직 및 성향테스트뷰 버튼 로직 구현(#43)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/AppDelegate.swift
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Protocols/.gitkeep
  Going-iOS/Global/Protocols/CheckPhotoAccessProtocol.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, ✨ Feat

#45 [FEAT] DOONavigationBar 구현 (#41)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/StartTravelSplashViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
Labels: 🐢 영서, ✨ Feat

#47 [FEAT] 할일 조회 & 할일 삭제 UI 및 기능 구현 (#39)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/UIComponents/DOOLabel.swift
  Going-iOS/Global/UIComponents/PaddingLabel.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ✨ Feat

#51 [FEAT] 토스트, 팝업 세팅 (#48)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Extensions/UIWindow+.swift
  Going-iOS/Global/UIComponents/DOOToast/DOOToast.swift
  Going-iOS/Global/UIComponents/DOOToast/DOOToastView.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/PopUp/DOOPopUpContainerView.swift
  Going-iOS/Scene/PopUp/DeleteUserPopUp/DeleteUserPopUpViewController.swift
  Going-iOS/Scene/PopUp/PopUpDimmedViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: ⚙️ Settings, 🦦 성준, ✨ Feat

#54 [FEAT] 여행생성뷰 여행날짜 관련 검증 로직 추가 구현
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
Labels: 🐢 영서, ✨ Feat

#60 [ FEAT] 텍스트필드 한글 이슈 해결(#55)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Extensions/String+.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
Labels: 🦦 성준, ✨ Feat

#57 [FEAT] 여행생성뷰 / 세팅뷰 - 토스트 및 팝업 구현 (#56)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Scene/CreateTravel/Models/CreateTravelStruct.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/PopUp/LogOutPopUp/LogOutPopUpViewController.swift
  Going-iOS/Scene/PopUp/PopUpDimmedViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
Labels: 🐢 영서, ✨ Feat

#59 [FEAT] 탭바 UI 및 기능 구현 (#50)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/Image.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/Image.imageset/btn_ourtodo_enabled_navi.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/Image.imageset/btn_ourtodo_enabled_navi@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/Image.imageset/btn_ourtodo_enabled_navi@3x.png
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/ManagerCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/TabBar/Views/TabBarView.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ✨ Feat

#63 [FEAT] 네비바 연결, 뷰 연결 (#61)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Scene/CompleteProfile/ViewControllers/CompleteProfileViewController.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, ✨ Feat

#65 [FEAT] 토스트 & 팝업 UI 및 기능 구현 (#62)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/PopUp/InviteFriendPopUp/InviteFriendPopUpViewController.swift
  Going-iOS/Scene/TabBar/Views/TabBarView.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/DoubleButtonView.swift
Labels: 👩 희슬, ✨ Feat

#68 [FEAT] 아워투두 & 마이투두 엠티뷰 UI 구현 (#66)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UILabel+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/empty_view_icon.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/empty_view_icon.imageset/empty_view_icon.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/empty_view_icon.imageset/empty_view_icon@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/OurToDo/empty_view_icon.imageset/empty_view_icon@3x.png
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/Models/MyToDoData.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/ManagerCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Models/OurToDoData.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/CreateNavigationBar.swift
  Going-iOS/Scene/OurToDo/Views/OurToDoHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/OurToDo/Views/UnderlineSegmentedControlView.swift
  Going-iOS/Scene/TabBar/Views/TabBarView.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ✨ Feat

#69 [FEAT] 카카오톡 초대코드 구현 / 내프로필뷰 구현 (#58)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/Constant.swift
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/ShowCreatedProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/MyResultView.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/InquiryWebViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/ServiceInfoWebViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/WebViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
Labels: 🐢 영서, ✨ Feat

#71 [Fix] 버튼 addTarget 오류 수정 (#70)
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
Labels: 🐢 영서, ⚒️ Fix

#67 [FEAT] 네트워크 레이어 구현(#64)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Literals/NameSpace.swift
  Going-iOS/Global/Protocols/DataTypeProtocol.swift
  Going-iOS/Global/Protocols/Serviceable.swift
  Going-iOS/Global/Protocols/ViewControllerServiceable.swift
  Going-iOS/Global/Settings/Configurations/Config.swift
  Going-iOS/Global/Settings/Configurations/Development.xcconfig
  Going-iOS/Network/Base/.gitkeep
  Going-iOS/Network/Base/BaseResponse.swift
  Going-iOS/Network/Base/HTTPHeaderField.swift
  Going-iOS/Network/Base/HTTPMethod.swift
  Going-iOS/Network/Base/NetworkError.swift
  Going-iOS/Network/Base/NetworkRequest.swift
  Going-iOS/Network/DTO/.gitkeep
  Going-iOS/Network/DTO/Auth/Token.swift
  Going-iOS/Network/Services/.gitkeep
  Going-iOS/Network/Services/ToDoService.swift
Labels: ⚙️ Settings, 🦦 성준, ✨ Feat

#79 [FEAT] 최종 GUI 반영 (#74)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/Splash/img_testsplash.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Splash/img_testsplash.imageset/img_testsplash.png
  Going-iOS/Global/Resources/Assets.xcassets/Splash/img_testsplash.imageset/img_testsplash@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Splash/img_testsplash.imageset/img_testsplash@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aei.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aei.imageset/img_testresult_aei1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aei.imageset/img_testresult_aei@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aei.imageset/img_testresult_aei@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aep.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aep.imageset/img_testresult_aep1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aep.imageset/img_testresult_aep@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_aep.imageset/img_testresult_aep@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_ari.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_ari.imageset/img_testresult_ari1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_ari.imageset/img_testresult_ari@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_ari.imageset/img_testresult_ari@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_arp.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_arp.imageset/img_testresult_arp1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_arp.imageset/img_testresult_arp@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_arp.imageset/img_testresult_arp@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sei.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sei.imageset/img_testresult_sei1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sei.imageset/img_testresult_sei@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sei.imageset/img_testresult_sei@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sep.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sep.imageset/img_testresult_sep1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sep.imageset/img_testresult_sep@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sep.imageset/img_testresult_sep@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sri.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sri.imageset/img_testresult_sri1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sri.imageset/img_testresult_sri@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_sri.imageset/img_testresult_sri@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_srp.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_srp.imageset/img_testresult_srp1.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_srp.imageset/img_testresult_srp@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/UserTestCharacterType/img_testresult_srp.imageset/img_testresult_srp@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/img_test.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/img_test.imageset/img_test.png
  Going-iOS/Global/Resources/Assets.xcassets/img_test.imageset/img_test@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/img_test.imageset/img_test@3x.png
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Global/UIComponents/DOOToast/DOOToastView.swift
  Going-iOS/Network/DTO/Profile/Response/GetProfileDTO.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/Models/UserTestQuestionStruct.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/Models/UserTypeTestResultAppData.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, ✨ Feat

#81 [FEAT] 아워투두 & 마이투두 서버 통신 (#76)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Settings/Info.plist
  Going-iOS/Network/DTO/MyToDo/GetMyToDoResponseDTO.swift
  Going-iOS/Network/DTO/OurToDo/GetOurToDoResponseDTO.swift
  Going-iOS/Network/Services/MyToDoService.swift
  Going-iOS/Network/Services/OurToDoService.swift
  Going-iOS/Scene/MyToDo/Models/MyToDoHeaderAppData.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Models/OurToDoHeaderAppData.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
Labels: 🌐 Network

#85 [FEAT] 애플 로그인 구현 (#84)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/AppDelegate.swift
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Protocols/Serviceable.swift
  Going-iOS/Global/UserDefault/IsAppleLogined.swift
  Going-iOS/Global/UserDefault/UserDefaultToken.swift
  Going-iOS/Network/Base/BaseResponse.swift
  Going-iOS/Network/DTO/Auth/Request/SignUpRequestDTO.swift
  Going-iOS/Network/DTO/Auth/Response/SignUpResponseDTO.swift
  Going-iOS/Network/DTO/OurToDo/GetOurToDoResponseDTO.swift
  Going-iOS/Network/Services/AuthService.swift
  Going-iOS/Network/Services/MyToDoService.swift
  Going-iOS/Network/Services/OurToDoService.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/MakeProfile/Models/UserProfileAppData.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
Labels: 🦦 성준, 🌐 Network, ✨ Feat

#88 [FEAT] 투두 조회 서버 통신 #82
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/ToDo/ic_lock.imageset/ic_lock@3x.png
  Going-iOS/Network/DTO/OurToDo/GetOurToDoResponseDTO.swift
  Going-iOS/Network/DTO/ToDo/GetDetailToDoResponseDTO.swift
  Going-iOS/Network/DTO/ToDo/GetToDoResponseDTO.swift
  Going-iOS/Network/Services/OurToDoService.swift
  Going-iOS/Network/Services/ToDoService.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Models/OurToDoHeaderAppData.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/ToDo/Cells/ToDoManagerCollectionViewCell.swift
  Going-iOS/Scene/ToDo/Models/DetailToDoAppData.swift
  Going-iOS/Scene/ToDo/Models/ToDoAppData.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, 🌐 Network

#91 [FEAT] 스플래시 분기처리 API 연결 (#86)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Protocols/Serviceable.swift
  Going-iOS/Network/Base/NetworkError.swift
  Going-iOS/Network/DTO/Splash/Response/SplashResponseDTO.swift
  Going-iOS/Network/Services/SplashService.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
Labels: 🦦 성준, 🌐 Network, ✨ Feat

#94 [FEAT] 로그인뷰, 프로필생성뷰 분기처리, 로그아웃 API연결 (#92)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Protocols/Serviceable.swift
  Going-iOS/Network/Base/NetworkError.swift
  Going-iOS/Network/Base/NetworkErrorCode.swift
  Going-iOS/Network/Base/NetworkRequest.swift
  Going-iOS/Network/DTO/Auth/Response/LogoutResponseDTO.swift
  Going-iOS/Network/Services/AuthService.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/PopUp/LogOutPopUp/LogOutPopUpViewController.swift
Labels: 🦦 성준, 🌐 Network, ✨ Feat

#93 [FEAT] 여행생성 / 여행전체 조회 API 서버 통신 (#89)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/DTO/Trip/Request/CreateTravelRequestDTO.swift
  Going-iOS/Network/DTO/Trip/Request/TravelQuery.swift
  Going-iOS/Network/DTO/Trip/Response/CreateTravelResponseDTO.swift
  Going-iOS/Network/DTO/Trip/Response/DashBoardResponseSturct.swift
  Going-iOS/Network/Services/TravelService.swift
  Going-iOS/Scene/CreateTravel/Models/CreateTravelRequestAppData.swift
  Going-iOS/Scene/CreateTravel/Models/CreateTravelResponseAppData.swift
  Going-iOS/Scene/CreateTravel/Models/CreatingSuccessAppData.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/DashBoard/Models/TravelInfoStruct.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
Labels: 🐢 영서, 🌐 Network, ✨ Feat

#97 [FEAT] 전체 투두 API 연결 적용 (#82)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/DTO/OurToDo/GetOurToDoResponseDTO.swift
  Going-iOS/Network/DTO/ToDo/Request/GetToDoRequestDTO.swift
  Going-iOS/Network/DTO/ToDo/Response/GetDetailToDoResponseDTO.swift
  Going-iOS/Network/DTO/ToDo/Response/GetToDoResponseDTO.swift
  Going-iOS/Network/Services/OurToDoService.swift
  Going-iOS/Network/Services/ToDoService.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/ManagerCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Models/OurToDoHeaderAppData.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/ToDo/Models/DetailToDoAppData.swift
  Going-iOS/Scene/ToDo/Models/ToDoAppData.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ✨ Feat

#100 [FEAT] 프로필 조회 API, 프로필 성향 테스트 API 연결 (#96)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Network/DTO/Auth/Response/SuccessResponseDTO.swift
  Going-iOS/Network/DTO/Profile/Request/TravelTypeTestRequestDTO.swift
  Going-iOS/Network/DTO/Profile/Response/GetProfileDTO.swift
  Going-iOS/Network/Services/OnBoardingService.swift
  Going-iOS/Network/Services/SplashService.swift
  Going-iOS/Network/Services/TravelService.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/Models/UserTypeTestResultAppData.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultTicketView.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, 🌐 Network, ✨ Feat

#103 [Feat] 여행 To Do 완료 & 미완료 서버 통신 (#98)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/DTO/ToDo/Response/GetCompleteToDoResponseDTO.swift
  Going-iOS/Network/Services/MyToDoService.swift
  Going-iOS/Network/Services/ToDoService.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/ShowCreatedProfileViewController.swift
  Going-iOS/Scene/MyProfile/Views/MyResultView.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/Models/MyToDoHeaderAppData.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/ToDo/Models/DetailToDoAppData.swift
  Going-iOS/Scene/ToDo/Models/ToDoAppData.swift
Labels: 🌐 Network

#105 [FEAT] 여행친구 전체조회 API 연결 (#102)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Network/DTO/Trip/Response/MemberResponseStruct.swift
  Going-iOS/Network/Services/MemberService.swift
  Going-iOS/Network/Services/TravelService.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/DashBoard/Views/DashBoardHeaderView.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Member/Models/MemberTestStruct.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/Member/Views/MemberProgressView.swift
  Going-iOS/Scene/Member/Views/MemberTestResultView.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/Settings/Models/SettingsItem.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
Labels: 🐢 영서, 🌐 Network, ✨ Feat

#108 [FEAT] AppIcon 및 BundleDisplayName 추가 (#107)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/102.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Going-iOS/Global/Settings/Info.plist
Labels: 🐢 영서, ✨ Feat

#117 [FEAT] 네트워크 에러 핸들링 모든 뷰컨 적용 (#110)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/Base/NetworkError.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelTestViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/PopUp/DeleteUserPopUp/DeleteUserPopUpViewController.swift
  Going-iOS/Scene/PopUp/LogOutPopUp/LogOutPopUpViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, 🌐 Network, ✨ Feat

#120 [FEAT] 여행 중 로직 / 카카오톡 템플릿 / 한글 글자수 세기 구현 (#116)
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/108.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/234.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/258.png
  Going-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/Models/TravelInfoStruct.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 🐢 영서, ✨ Feat

#122 [FEAT] TabbarController 로직 (#121)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo.imageset/mytodo.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo.imageset/mytodo@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo.imageset/mytodo@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo_unselected.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo_unselected.imageset/mytodo_unselected.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo_unselected.imageset/mytodo_unselected@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/mytodo_unselected.imageset/mytodo_unselected@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/tabbar_mytodo_selected.imageset/btn_mytodo_enabled_navi.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/tabbar_mytodo_selected.imageset/btn_mytodo_enabled_navi@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/tabbar_mytodo_selected.imageset/btn_mytodo_enabled_navi@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/tabbar_mytodo_unselected.imageset/btn_mytodo_disabled_navi.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/tabbar_mytodo_unselected.imageset/btn_mytodo_disabled_navi@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/tabbar/tabbar_mytodo_unselected.imageset/btn_mytodo_disabled_navi@3x.png
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Global/UIComponents/DOOTabbarViewController.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
Labels: 🦦 성준, ✨ Feat

#123 [FEAT] 키보드 감지 및 올리기 (#114)
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ✨ Feat

#127 [FEAT] 데이트피커 날짜 검증 수정 구현 (#125)
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/CreateTravel/Views/DatePickerView.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 🐢 영서, ✨ Feat

#130 [FEAT]로띠 라이브러리 설치 및 인디케이터(로딩뷰) (#124)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Going-iOS/Global/Protocols/ViewControllerServiceable.swift
Labels: 🦦 성준, ✨ Feat

#133 [FEAT] 데이트피커 관련 로직 수정 (#132)
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 🐢 영서, ✨ Feat

#134 [FEAT] rootVC 분기처리(#131)
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
Labels: 🦦 성준, ✨ Feat

#137 [Fix] datePicker 이슈 해결(#136)
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ✨ Feat, ⚒️ Fix

#138 [FIX] 추가 수정사항 #135
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/img_mytodo_empty.imageset/img_mytodo_empty.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/img_mytodo_empty.imageset/img_mytodo_empty@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/MyToDo/img_mytodo_empty.imageset/img_mytodo_empty@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/yesbtn_ourtodo_navi.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/yesbtn_ourtodo_navi.imageset/yesbtn_ourtodo_navi 1.svg
  Going-iOS/Global/Resources/Assets.xcassets/yesbtn_ourtodo_navi.imageset/yesbtn_ourtodo_navi 2.svg
  Going-iOS/Global/Resources/Assets.xcassets/yesbtn_ourtodo_navi.imageset/yesbtn_ourtodo_navi.svg
  Going-iOS/Global/UIComponents/DOOTabbarViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelTestViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/PopUp/LogOutPopUp/LogOutPopUpViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/TravelTestViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, ✨ Feat

#142 [FIX] 1차 QA 적용 (#141)
  Going-iOS/Global/Extensions/UIView+.swift
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 👩 희슬, ⚒️ Fix

#144 [FIX] QA 1차( 탭바, 회원탈퇴 로직) (#140)
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Settings/ViewControllers/SettingsViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🦦 성준, ⚒️ Fix

#146 [FIX] version change
  Going-iOS.xcodeproj/project.pbxproj
Labels: 🦦 성준, 👩 희슬, 🐢 영서, ⚒️ Fix

#147 [Fix]
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Settings/Info.plist
Labels: 🦦 성준, 👩 희슬, 🐢 영서, ⚒️ Fix

#149 [Hotfix] 이름을 닉네임으로 변경(#148)
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
Labels: 🦦 성준, ⚒️ Fix

#150 [Hotfix] 이름을 닉네임으로 수정(1.0.0 버전 )
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
Labels: 🦦 성준, ⚒️ Fix

#156 [HOTFIX] 데이트피커 인디케이터 이슈 해결 및 라이팅 체크 (#155)
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/PopUp/DeleteUserPopUp/DeleteUserPopUpViewController.swift
  Going-iOS/Scene/StartTravel/ViewControllers/StartTravelSplashViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🐢 영서, 🛠️ Hotfix

#154 [HOTFIX] 1차 QA 기기대응 (#151)
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/img_tripsplash.imageset/img_tripsplash.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/img_tripsplash.imageset/img_tripsplash@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/img_tripsplash.imageset/img_tripsplash@3x.png
  Going-iOS/Global/UIComponents/DOOTabbarViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/StartTravel/ViewControllers/StartTravelSplashViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 👩 희슬, 🛠️ Hotfix

#157 [HOTFIX] 1차 릴리즈 QA - 카카오로그인 버튼, 메모 입력 제한 (#153)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UIColor+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_large_wide.imageset/kakao_login_large_wide@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_large_wide.imageset/kakao_login_large_wide@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/kakaologo 2.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/kakaologo 2@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/kakaologo 2@3x.png
  Going-iOS/Global/Settings/Info.plist
  Going-iOS/Network/Base/NetworkError.swift
  Going-iOS/Network/DTO/ToDo/Response/GetDetailToDoStruct.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelTestViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, 🛠️ Hotfix

#161 [FEAT] 스플래시 로티 추가 (#159)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Scene/Login/SplashLottie/dooripsplash2.json
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 👩 희슬, ✨ Feat

#162 [FEAT] 프로필뷰 닉네임 데이터 통신 및 레이아웃 수정
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/PopUp/DeleteUserPopUp/DeleteUserPopUpViewController.swift
  Going-iOS/Scene/PopUp/InviteFriendPopUp/InviteFriendPopUpViewController.swift
  Going-iOS/Scene/StartTravel/Models/TravelTestQuestionStruct.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/Models/UserTypeTestResultAppData.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🐢 영서, ✨ Feat, ⚒️ Fix

#163 [Hotfix] 성향테스트뷰 이슈 해결(#160)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/Services/OnBoardingService.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, 🛠️ Hotfix

#164 [UPDATE] 1.0.1 버전 출시
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Global/Extensions/UIColor+.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Literals/StringLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_large_wide.imageset/kakao_login_large_wide@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakao_login_large_wide.imageset/kakao_login_large_wide@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/kakaologo 2.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/kakaologo 2@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/kakaologo.imageset/kakaologo 2@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/img_tripsplash.imageset/img_tripsplash.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/img_tripsplash.imageset/img_tripsplash@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/TravelEntranceSplash/img_tripsplash.imageset/img_tripsplash@3x.png
  Going-iOS/Global/Settings/Info.plist
  Going-iOS/Global/UIComponents/DOOTabbarViewController.swift
  Going-iOS/Network/Base/NetworkError.swift
  Going-iOS/Network/DTO/ToDo/Response/GetDetailToDoStruct.swift
  Going-iOS/Network/Services/OnBoardingService.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelTestViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Login/SplashLottie/dooripsplash2.json
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Member/ViewControllers/MemberViewController.swift
  Going-iOS/Scene/MyProfile/ViewControllers/MyProfileViewController.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/PopUp/DeleteUserPopUp/DeleteUserPopUpViewController.swift
  Going-iOS/Scene/PopUp/InviteFriendPopUp/InviteFriendPopUpViewController.swift
  Going-iOS/Scene/StartTravel/Models/TravelTestQuestionStruct.swift
  Going-iOS/Scene/StartTravel/ViewControllers/StartTravelSplashViewController.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/Models/UserTypeTestResultAppData.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
  Going-iOS/Scene/UserTestResult/Views/TestResultView.swift
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🚀 Update

#167 [HOTFIX] 여행성향테스트 결과조회뷰 닉네임 서버통신 오류 수정 (#166)
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🐢 영서, 🛠️ Hotfix

#168 [HOTFIX] 자체 QA 이슈 (#165)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/Services/ToDoService.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
Labels: 🦦 성준, 🛠️ Hotfix

#170 [UPDATE] 1.0.2 버전 업데이트 (#169)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/Services/ToDoService.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestSplashViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🚀 Update

#171 [Chore] 빌드 번호 변경
  Going-iOS.xcodeproj/project.pbxproj
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🚀 Update

#174 [HOTFIX] 1.0.2 QA (#173)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/Login/SplashLottie/dooripsplash2.json
  Going-iOS/Scene/Login/SplashLottie/dooripsplash3.json
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Member/Models/MemberTestStruct.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/Models/TravelTestQuestionStruct.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/Models/UserTestQuestionStruct.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 👩 희슬, 🛠️ Hotfix

#175 [HOTFIX] 1.0.2 QA (#172)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/AppDelegate.swift
  Going-iOS/Network/Base/NetworkCheck.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🦦 성준, 🛠️ Hotfix

#177 [UPDATE] 1.0.3 업데이트
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Application/AppDelegate.swift
  Going-iOS/Network/Base/NetworkCheck.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoiningSuccessViewController.swift
  Going-iOS/Scene/Login/SplashLottie/dooripsplash2.json
  Going-iOS/Scene/Login/SplashLottie/dooripsplash3.json
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/MakeProfile/ViewControllers/MakeProfileViewController.swift
  Going-iOS/Scene/Member/Models/MemberTestStruct.swift
  Going-iOS/Scene/StartTravel/Cells/TravelTestCollectionViewCell.swift
  Going-iOS/Scene/StartTravel/Models/TravelTestQuestionStruct.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/UserTest/Models/UserTestQuestionStruct.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
  Going-iOS/Scene/UserTestResult/ViewControllers/UserTestResultViewController.swift
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🚀 Update

#181 [HOTFIX] 빌드번호, 버전 업데이트(#180)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/ViewController.swift
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🛠️ Hotfix, 🚀 Update

#183 [UPDATE] 1.0.4 업데이트
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Network/DTO/Trip/Request/JoinTravelTestRequestStruct.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelTestViewController.swift
  Going-iOS/ViewController.swift
Labels: 🦦 성준, 👩 희슬, 🐢 영서, 🚀 Update

#187 [CHORE] 코드 정리 (#184)
  Going-iOS/Global/Literals/Constant.swift
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Scene/CreateTravel/Models/CreateTravelStruct.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreateTravelViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/CreatingSuccessViewController.swift
  Going-iOS/Scene/CreateTravel/ViewControllers/DatePickerBottomSheetViewController.swift
  Going-iOS/Scene/DashBoard/Cells/DashBoardCollectionViewCell.swift
  Going-iOS/Scene/DashBoard/ViewControllers/DashBoardViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelTestViewController.swift
  Going-iOS/Scene/JoinTravel/ViewControllers/JoinTravelViewController.swift
  Going-iOS/Scene/Member/Views/MemberTestResultView.swift
Labels: 🐢 영서, ✨ Feat

#188 [UPDATE] 1.1.0 업데이트 (#186)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS.xcodeproj/xcshareddata/xcschemes/Going-iOS.xcscheme
  Going-iOS/Application/SceneDelegate.swift
  Going-iOS/Global/Literals/ImageLiterals.swift
  Going-iOS/Global/Resources/Assets.xcassets/Login/loginLogo.imageset/Contents.json
  Going-iOS/Global/Resources/Assets.xcassets/Login/loginLogo.imageset/loginLogo.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/loginLogo.imageset/loginLogo@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/loginLogo.imageset/loginLogo@3x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/login_logo.imageset/login_logo.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/login_logo.imageset/login_logo@2x.png
  Going-iOS/Global/Resources/Assets.xcassets/Login/login_logo.imageset/login_logo@3x.png
  Going-iOS/Global/UIComponents/DOONavigationBar.swift
  Going-iOS/Network/Base/NetworkRequest.swift
  Going-iOS/Scene/Login/Cells/.gitkeep
  Going-iOS/Scene/Login/Models/.gitkeep
  Going-iOS/Scene/Login/ViewControllers/LoginViewController.swift
  Going-iOS/Scene/Login/ViewControllers/SplashViewController.swift
  Going-iOS/Scene/Login/Views/.gitkeep
  Going-iOS/Scene/Settings/Cells/SettingsCollectionViewCell.swift
  Going-iOS/Scene/UserTest/ViewControllers/UserTestViewController.swift
Labels: 🦦 성준, 🚀 Update

#191 [FEAT] 주석 정리 (#185)
  Going-iOS.xcodeproj/project.pbxproj
  Going-iOS/Scene/MyToDo/Cells/MyToDoCollectionViewCell.swift
  Going-iOS/Scene/MyToDo/Models/MyToDoData.swift
  Going-iOS/Scene/MyToDo/Models/MyToDoHeaderAppData.swift
  Going-iOS/Scene/MyToDo/ViewControllers/MyToDoViewController.swift
  Going-iOS/Scene/OurToDo/Cells/OurToDoCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Cells/TripFriendsCollectionViewCell.swift
  Going-iOS/Scene/OurToDo/Models/FriendProfileData.swift
  Going-iOS/Scene/OurToDo/Models/OurToDoData.swift
  Going-iOS/Scene/OurToDo/ViewControllers/OurToDoViewController.swift
  Going-iOS/Scene/OurToDo/Views/OurToDoHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripHeaderView.swift
  Going-iOS/Scene/OurToDo/Views/TripMiddleView.swift
  Going-iOS/Scene/ToDo/Models/DetailToDoAppData.swift
  Going-iOS/Scene/ToDo/Models/ToDoAppData.swift
  Going-iOS/Scene/ToDo/Models/ToDoData.swift
  Going-iOS/Scene/ToDo/ViewControllers/ToDoViewController.swift
  Going-iOS/Scene/ToDo/Views/DoubleButtonView.swift
Labels: 👩 희슬, ✨ Feat
